/**
 * All landing-page and Code-a-Pookalam copy, in one editable place.
 *
 * Kept out of the JSX deliberately: the words are not final and will change
 * several times before launch, and whoever edits them should not have to read
 * a component to do it. Nothing here is used for logic — game behaviour lives
 * in `src/server/games/registry.ts`.
 *
 * PLACEHOLDER VALUES are marked TODO. Dates, prize amounts and links must be
 * confirmed before this goes public.
 */

export const EVENT = {
  name: "FOSS Onam Games",
  tagline: "Seven days. Six games. One pookalam. Zero dignity.",
  blurb:
    "A week of daily games for Onam, run by the FOSS club. Every day a new game unlocks, everyone plays the same puzzle, and the fastest solve wins. Come for the prizes, stay because you cannot let your friend beat you.",
  // TODO: confirm before launch.
  dates: "TODO — event dates",
  registerNote: "Sign in with Google. Takes about eleven seconds.",

  howItWorks: [
    {
      title: "A game a day",
      body: "One new game unlocks every evening. It stays open for 24 hours, then it's gone.",
    },
    {
      title: "Everyone gets the same puzzle",
      body: "Same difficulty for everybody, shuffled so you can't win by copying a screenshot from the group chat.",
    },
    {
      title: "The clock is ours",
      body: "The timer runs on the server. Refresh, close the tab, throw your phone — it keeps counting.",
    },
    {
      title: "Points, not seconds",
      body: "Each day you score on where you finished, not raw time. That's how a jigsaw and a jumping king end up on the same leaderboard.",
    },
  ],

  scoring: {
    title: "How scoring actually works",
    body: "Every game gives up to 1050 points, based on how much of the field you beat that day. Finish first out of 200 and you get the lot. Finish dead last and you still get 50 for turning up. Miss a day and you get nothing, which is the entire retention strategy.",
    aside: "yes we thought about this way too hard",
  },

  // TODO: confirm prizes and amounts with whoever controls the budget.
  prizes: [
    { rank: "Overall winner", detail: "TODO — top of the weekly points table" },
    { rank: "Runners-up", detail: "TODO — 2nd and 3rd overall" },
    { rank: "Daily winners", detail: "TODO — fastest on each individual day" },
    { rank: "Code-a-Pookalam", detail: "TODO — separate prize pool" },
  ],

  rules: [
    "One account per person. One account per device. We check both.",
    "Don't script it. The server can tell, and it keeps receipts.",
    "Sharing answers ruins the day for everyone, including you, because it's ranked.",
    "Getting caught means a warning, then a bench, then you're out.",
    "Organisers and testers play early and never appear on your leaderboard.",
  ],

  faq: [
    {
      q: "Do I need to know how to code?",
      a: "For the games, no. Not even slightly. For Code-a-Pookalam, yes — that one's the whole point.",
    },
    {
      q: "I missed a day. Am I finished?",
      a: "Not finished, just behind. A missed day is zero points and there's no make-up round, but the week is long and people fall off constantly.",
    },
    {
      q: "Can I play on my phone?",
      a: "That's mostly what we built it for. Every game works on a phone.",
    },
    {
      q: "Is this only for MEC students?",
      a: "No. Anyone can play — pick 'Other' when you sign up and tell us where you're from.",
    },
    {
      q: "What if I find a bug?",
      a: "Tell us. Finding a bug is fine. Quietly farming one is not, and it's the fastest route to a ban.",
    },
  ],
} as const;

/**
 * The Code-a-Pookalam competition — the one event that isn't a timed game.
 * Runs alongside the week and is judged separately.
 */
export const POOKALAM = {
  title: "Code-a-Pookalam",
  tagline: "Draw a pookalam. With code. No image editors, no cheating, no mercy.",
  blurb:
    "A pookalam is a flower carpet laid out on the ground for Onam — radial, symmetric, and absurdly intricate. Your job is to produce one entirely in code. No image files, no tracing, no AI-generated PNG you found. Just geometry, colour, and whatever patience you have left.",

  // TODO: confirm all dates.
  submitBy: "TODO — submission deadline",
  votingOn: "TODO — public voting day",

  rules: [
    "Everything must be generated by your code. No raster assets, no imported artwork.",
    "Any language, any framework, any renderer. Canvas, SVG, p5, turtle, shader, ASCII — your call.",
    "The output must be a pookalam: radial and symmetric. A gradient square is not a pookalam.",
    "Submit the source, not just the picture. We run it.",
    "Original work only. We will notice if it's a lightly recoloured tutorial.",
  ],

  judging: [
    { name: "Visual impact", body: "Does it stop you scrolling?" },
    {
      name: "Technical craft",
      body: "Is the code doing something interesting, or is it 400 hardcoded circles?",
    },
    { name: "Symmetry & structure", body: "Does it read as a real pookalam?" },
    { name: "Originality", body: "Have we seen this exact thing on a tutorial site?" },
  ],

  votingBlurb:
    "Shortlisted entries go to public voting — head-to-head pairs, you pick the better one, ratings settle over the week. Entries stay anonymous while voting is open so nobody wins on friend count alone.",

  aside: "someone will submit a fractal. someone always submits a fractal.",
} as const;
