import type { GeneratedInstance, VerifyInput, VerifyResult } from "../registry";
import { createRng } from "../rng";

/**
 * Wend - a word puzzle that is really a tiling puzzle.
 *
 * THE RULES
 *
 * A grid of letters with a few walls. Six words are hidden in it, one of each
 * length from three to eight. A word is traced through orthogonally adjacent
 * tiles - up, down, left, right, never diagonally - and the path may bend as
 * often as it likes, winding around the walls.
 *
 * The constraint that makes it a puzzle rather than a word search: EVERY open
 * tile belongs to exactly one word. Words cannot overlap and no tile may be
 * left over. So a path that reads correctly can still be wrong, because it
 * stranded a tile that nothing else can now reach. Finding the words is half
 * the job; fitting them together is the other half.
 *
 * (This module previously implemented a straight-line word search with
 * diagonals and filler letters. That is a different, much easier game, and it
 * was simply the wrong one.)
 *
 * THE BOARD
 *
 * One canonical board for the whole event, shown to each player under one of
 * eight dihedral presentations chosen by their seed. Per-player boards were
 * rejected on the standing fairness rule: different boards mean different
 * difficulty, and a ranked day cannot be scored across puzzles that are not
 * equally hard. Rotation and reflection change what the board looks like
 * without changing one thing about how hard it is.
 *
 * The board itself is a frozen constant rather than something generated at
 * runtime. Constructing one is a backtracking search and *proving it has a
 * single solution* is a bigger one - seconds of work, which is fine offline and
 * unacceptable on a cold start. See `scripts/make-wend-board.mjs`.
 */

export const GRID_SIZE = 6;

/** Words to find. Order is irrelevant - the player finds them however they like. */
export const WORDS = ["GNU", "ONAM", "LINUX", "KERNEL", "PAYASAM", "POOKALAM"] as const;

/**
 * THE canonical board. Empty string is a wall.
 *
 * Generated by `node scripts/make-wend-board.mjs wend-canonical-v2` and verified
 * to have exactly one solution. Do not hand-edit: a single changed letter can
 * make it unsolvable or ambiguous, and neither failure is visible by eye.
 */
export const BOARD: readonly (readonly string[])[] = [
  ["A", "Y", "P", "O", "A", "L"],
  ["P", "A", "S", "O", "K", "A"],
  ["", "M", "A", "N", "R", "M"],
  ["M", "", "L", "E", "E", "K"],
  ["A", "U", "N", "U", "N", ""],
  ["N", "O", "G", "X", "I", "L"],
];

export interface Cell {
  r: number;
  c: number;
}

export interface WendTransform {
  /** Quarter-turns clockwise. */
  rot: 0 | 1 | 2 | 3;
  /** Mirror horizontally before rotating. */
  flip: boolean;
}

/** The player's presentation, derived from their seed. Eight possibilities. */
export function transformFor(seed: string): WendTransform {
  const rng = createRng(`${seed}:wend`);
  return { rot: rng.int(0, 3) as 0 | 1 | 2 | 3, flip: rng.chance(0.5) };
}

/**
 * Maps a canonical cell to where it appears on the player's board.
 *
 * Rotation and reflection both preserve orthogonal adjacency, which is why they
 * are safe here: a path that was legal on the canonical board is still a legal
 * path after the transform, with every bend intact.
 */
export function applyTransform(cell: Cell, t: WendTransform): Cell {
  let { r, c } = cell;
  const n = GRID_SIZE - 1;
  if (t.flip) c = n - c;
  for (let i = 0; i < t.rot; i += 1) {
    const nr = c;
    const nc = n - r;
    r = nr;
    c = nc;
  }
  return { r, c };
}

export interface WendView {
  kind: "wend";
  size: number;
  /** Transformed letters. An empty string is a wall. */
  grid: string[][];
  /**
   * How long each hidden word is, ascending. NOT the words themselves.
   *
   * Deducing which routes spell which words is the puzzle. An earlier version
   * shipped the word list to the browser, which gave the whole thing away -
   * with the answers in hand the board is a five-minute tracing exercise.
   * The player gets what the real game gives them: how many words, and how
   * long each one is.
   */
  wordLengths: number[];
  /** How many tiles must end up covered. Lets the UI show honest progress. */
  openCells: number;
}

export interface WendSubmission {
  /** One traced path per word the player claims to have found. */
  found: { word: string; cells: Cell[] }[];
}

/** The player's grid: the canonical board pushed through their transform. */
function displayGrid(seed: string): string[][] {
  const t = transformFor(seed);
  const grid: string[][] = Array.from({ length: GRID_SIZE }, () =>
    Array.from<string>({ length: GRID_SIZE }).fill(""),
  );
  for (let r = 0; r < GRID_SIZE; r += 1) {
    for (let c = 0; c < GRID_SIZE; c += 1) {
      const to = applyTransform({ r, c }, t);
      grid[to.r][to.c] = BOARD[r][c];
    }
  }
  return grid;
}

const countOpen = (grid: string[][]): number =>
  grid.reduce((n, row) => n + row.filter((cell) => cell !== "").length, 0);

export function generate(seed: string): GeneratedInstance {
  const grid = displayGrid(seed);
  return {
    view: {
      kind: "wend",
      size: GRID_SIZE,
      grid,
      wordLengths: [...WORDS].map((w) => w.length).sort((a, b) => a - b),
      openCells: countOpen(grid),
    } satisfies WendView,
    /*
     * Nothing to withhold. Verification is structural - it checks that the
     * submitted paths are legal and tile the board - so it never needs a stored
     * answer to compare against. That also means any genuinely valid solution
     * is accepted, not just the one the generator happened to find.
     */
    solution: null,
  };
}

const adjacent = (a: Cell, b: Cell): boolean => Math.abs(a.r - b.r) + Math.abs(a.c - b.c) === 1;

/**
 * Does this traced path spell one of the hidden words?
 *
 * Backs the mid-attempt trace endpoint. The words are the puzzle and are never
 * sent to the browser, so the client cannot answer this itself. Shipping hashes
 * instead would not help - an eight-letter uppercase word falls to a wordlist
 * in seconds - so the check is a server round trip.
 *
 * It returns only the word the player just traced, which they can read off
 * their own screen, and says nothing about the ones they have not found.
 * Nothing here is authoritative: the whole board is re-validated at finish, so
 * lying to this endpoint gains nothing.
 */
export function matchTrace(seed: string, cells: Cell[]): string | null {
  if (!Array.isArray(cells) || cells.length < 3) return null;
  const grid = displayGrid(seed);
  let word = "";
  for (let i = 0; i < cells.length; i += 1) {
    const cell = cells[i];
    if (
      typeof cell?.r !== "number" ||
      typeof cell?.c !== "number" ||
      !Number.isInteger(cell.r) ||
      !Number.isInteger(cell.c) ||
      cell.r < 0 ||
      cell.r >= GRID_SIZE ||
      cell.c < 0 ||
      cell.c >= GRID_SIZE
    ) {
      return null;
    }
    if (grid[cell.r][cell.c] === "") return null;
    if (i > 0 && !adjacent(cells[i - 1], cell)) return null;
    word += grid[cell.r][cell.c];
  }
  return (WORDS as readonly string[]).includes(word) ? word : null;
}

export function verify(input: VerifyInput): VerifyResult {
  const submission = input.submission as WendSubmission | null;
  if (!submission || !Array.isArray(submission.found)) {
    return { valid: false, reason: "Nothing submitted." };
  }
  if (submission.found.length !== WORDS.length) {
    return { valid: false, reason: "Some words are still hiding." };
  }

  // Rebuilt from the player's own seed, so a path copied from someone else's
  // board lands on the wrong letters and fails on its own merits.
  const grid = displayGrid(input.seed);
  const remaining = new Set<string>(WORDS);
  const claimed = new Set<string>();

  for (const entry of submission.found) {
    if (typeof entry?.word !== "string" || !Array.isArray(entry.cells)) {
      return { valid: false, reason: "Malformed submission." };
    }
    if (!remaining.delete(entry.word)) {
      return { valid: false, reason: "That is not one of the words." };
    }
    if (entry.cells.length !== entry.word.length) {
      return { valid: false, reason: `"${entry.word}" does not fit that path.` };
    }

    for (let i = 0; i < entry.cells.length; i += 1) {
      const cell = entry.cells[i];
      if (
        typeof cell?.r !== "number" ||
        typeof cell?.c !== "number" ||
        !Number.isInteger(cell.r) ||
        !Number.isInteger(cell.c) ||
        cell.r < 0 ||
        cell.r >= GRID_SIZE ||
        cell.c < 0 ||
        cell.c >= GRID_SIZE
      ) {
        return { valid: false, reason: "Malformed submission." };
      }
      if (grid[cell.r][cell.c] !== entry.word[i]) {
        return { valid: false, reason: `"${entry.word}" is not there. ENTHUVA!` };
      }
      // Steps must be orthogonal and one tile long - the path may bend, but it
      // may never jump or cut a corner.
      if (i > 0 && !adjacent(entry.cells[i - 1], cell)) {
        return { valid: false, reason: `"${entry.word}" does not join up.` };
      }
      const key = `${cell.r},${cell.c}`;
      if (claimed.has(key)) {
        return { valid: false, reason: "Two words are sharing a tile." };
      }
      claimed.add(key);
    }
  }

  // The tiling condition, and the only rule that makes this Wend rather than a
  // word search: nothing may be left over.
  if (claimed.size !== countOpen(grid)) {
    return { valid: false, reason: "Some tiles are still empty." };
  }

  return { valid: true, movesCount: submission.found.length };
}

/** Exposed for tests and a future admin preview. */
export function canonicalGridForTest(): string[][] {
  return BOARD.map((row) => [...row]);
}
